"""change qa_leader

Revision ID: 1f78a8e04e4c
Revises: 8d0e597cd83c
Create Date: 2018-08-19 18:03:15.210510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f78a8e04e4c'
down_revision = '8d0e597cd83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Qa', sa.Column('group_name', sa.String(length=128), nullable=True))
    op.drop_constraint('phone_ibfk_1', 'phone', type_='foreignkey')
    op.create_foreign_key(None, 'phone', 'Qa', ['qa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone', type_='foreignkey')
    op.create_foreign_key('phone_ibfk_1', 'phone', 'qa', ['qa_id'], ['id'])
    op.drop_column('Qa', 'group_name')
    # ### end Alembic commands ###
