"""add for 

Revision ID: 30ae2ebf83ce
Revises: 618d7df12f0a
Create Date: 2018-08-07 22:17:10.627438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30ae2ebf83ce'
down_revision = '618d7df12f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone', 'machine_pinpai1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone', sa.Column('machine_pinpai1', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
