"""add phone

Revision ID: 33e706a27d4a
Revises: cbcf703c3f9f
Create Date: 2018-08-04 21:58:16.094960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e706a27d4a'
down_revision = 'cbcf703c3f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_os', sa.String(length=128), nullable=True),
    sa.Column('machine_year', sa.String(length=128), nullable=True),
    sa.Column('machine_pinpai', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone')
    # ### end Alembic commands ###
