"""add for 

Revision ID: 618d7df12f0a
Revises: 33e706a27d4a
Create Date: 2018-08-07 22:15:21.847963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618d7df12f0a'
down_revision = '33e706a27d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone', sa.Column('machine_pinpai1', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone', 'machine_pinpai1')
    # ### end Alembic commands ###
