"""leader city

Revision ID: 74884aed293e
Revises: a7545b155624
Create Date: 2018-08-19 16:06:11.377202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74884aed293e'
down_revision = 'a7545b155624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('phone_ibfk_1', 'phone', type_='foreignkey')
    op.create_foreign_key(None, 'phone', 'Qa', ['qa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone', type_='foreignkey')
    op.create_foreign_key('phone_ibfk_1', 'phone', 'qa', ['qa_id'], ['id'])
    # ### end Alembic commands ###
