"""add for 

Revision ID: 83b9bf3d0d5e
Revises: 30ae2ebf83ce
Create Date: 2018-08-07 22:20:31.275346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b9bf3d0d5e'
down_revision = '30ae2ebf83ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone', sa.Column('qa_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'phone', 'Qa', ['qa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone', type_='foreignkey')
    op.drop_column('phone', 'qa_id')
    # ### end Alembic commands ###
