"""leader

Revision ID: b0559d64ed75
Revises: 3499239190fd
Create Date: 2018-08-19 16:00:33.927297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0559d64ed75'
down_revision = '3499239190fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('phone_ibfk_1', 'phone', type_='foreignkey')
    op.create_foreign_key(None, 'phone', 'Qa', ['qa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone', type_='foreignkey')
    op.create_foreign_key('phone_ibfk_1', 'phone', 'qa', ['qa_id'], ['id'])
    # ### end Alembic commands ###
