"""add qa

Revision ID: cbcf703c3f9f
Revises: 53d82c1c1647
Create Date: 2018-08-02 21:29:42.798512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbcf703c3f9f'
down_revision = '53d82c1c1647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('age', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Qa_name'), 'Qa', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Qa_name'), table_name='Qa')
    op.drop_table('Qa')
    # ### end Alembic commands ###
